version: 2 
jobs: 
  build:
    machine: true
    steps:
      - checkout
        - run:
           name: Setup Environment Variables
           command: |
             echo $CIRCLE_SHA1      
             echo $GIT_SHA1      
             echo 'export GIT_SHA1="$CIRCLE_SHA1"' >> $BASH_ENV
             echo $CIRCLE_SHA1      
             echo $GIT_SHA1      
        #- run: docker build -t jab2805rakuten/helloworld-1:v0.0.1 .    
