version: 2 
jobs: 
  build:
    machine: true
    steps:
      - checkout
        #  - run:
         #name: Setup Environment Variables
         #ommand: |
         # echo 'export GIT_SHA1="$CIRCLE_SHA1"' >> $BASH_ENV
      - run: docker build -t jab2805rakuten/helloworld-1:v0.0.1 .    
      - run: docker images   
