version: 2 
jobs: 
  build:
    machine: true
    steps:
      - checkout
      - run: 
         name: Setup Env
         command: |
              echo 'export GIT_SHA1="$CIRCLE_SHA1"' >> $BASH_ENV   
      - run: docker build -t jab2805rakuten/helloworld-1:${CIRCLE_SHA1} .    
      - run: docker images     
      - run: docker run -p 3000:3000 -d jab2805rakuten/helloworld-1:${CIRCLE_SHA1}     
      - run:      
         name: Setup Env
         command: |
              echo 'export AWS_ACCESS_KEY_ID="$AWS_ACCESS_KEY_ID"' >> $BASH_ENV   
              echo 'export AWS_SECRET_ACCESS_KEY="$AWS_SECRET_ACCESS_KEY"' >> $BASH_ENV   

      - run:      
         command: |
           eval  $(aws ecr get-login --region us-east-1 --no-include-email) 
           docker tag  jab2805rakuten/helloworld-1:${CIRCLE_SHA1} 90O3397269197.dkr.ecr.us-east-1.amazonaws.com/jab2805rakuten/helloworld-1:${CIRCLE_SHA1}
           docker push 90O3397269197.dkr.ecr.us-east-1.amazonaws.com/jab2805rakuten/helloworld-1:${CIRCLE_SHA1}
