version: 2 
jobs: 
  build:
    machine: true
    steps:
      - checkout
      - run: 
         name: Setup Env
         command: |
              echo 'export GIT_SHA1="$CIRCLE_SHA1"' >> $BASH_ENV   
      - run: docker build -t jab2805rakuten/helloworld-1:${CIRCLE_SHA1} .    
      - run: docker images     
      - run: docker run -p 3000:3000 -d jab2805rakuten/helloworld-1:${CIRCLE_SHA1}     
      - run: curl -I 127.0.0.1:3000     


